#!/usr/bin/env node
import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { parseArgs } from "node:util";
import { generateDefaultImports, generateTheme } from "./generate.js";

const pwd = process.cwd();

// Define CLI options
const options = {
	output: {
		type: "string",
		short: "o",
		default: "theme.css",
		description: "Output file name",
	},
	"no-imports": {
		type: "boolean",
		default: false,
		description:
			"Specify whether default imports should be added to the output file",
	},
	"no-tw-defaults": {
		type: "string",
		default: "",
		description:
			"Specify namespace(s) for default Tailwind variables that should not be generated",
	},
};

// Parse command line arguments
const { values, positionals } = parseArgs({ options, allowPositionals: true });

if (positionals.length === 0) {
	console.error("Please provide a theme file path");
	process.exit(1);
}

const inputFile = positionals[0];
const outputFile = values.output;
const defaultsToExclude = values["no-tw-defaults"].split(",");

try {
	console.time(`✅ Successfully generated ${outputFile}`);
	// Read the input theme file
	const themePath = resolve(pwd, inputFile);

	// Convert file path to URL for ESM import compatibility
	const themeURL = pathToFileURL(themePath);

	// Execute the theme file content to get the theme object
	const themeModule = await import(themeURL);
	const theme =
		themeModule.theme ??
		themeModule.default?.default ??
		themeModule.default ??
		themeModule.default?.theme ??
		themeModule.default?.default?.theme;

	if (!theme) {
		console.error(
			"No theme found in the input file; please ensure the file exports a valid theme object",
		);
		process.exit(1);
	}

	let css =
		"/** This file is autogenerated by the script. Do not edit it manually. */\n";

	if (!values["no-imports"]) {
		css += generateDefaultImports();
	}

	// Generate CSS from theme object
	css += generateTheme(theme, defaultsToExclude);

	// Write to output file
	const outputPath = resolve(pwd, outputFile);
	await writeFile(outputPath, css);

	console.timeEnd(`✅ Successfully generated ${outputFile}`);
} catch (error) {
	console.error("Error generating theme:", error.message);
	process.exit(1);
}
